server:
  port: 9000
spring: 
  application: 
    name: ribbon-client
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hotel-service: 
  eureka: 
    enabled: false
  listofServers: localhost:8081,localhost:8082,localhost:8085
    
